/*
 * Default Configuration Values for Advanced Systems
 * Sets up default configuration for all advanced systems
 */

#ifndef ADVANCED_SYSTEMS_DEFAULTS_H
#define ADVANCED_SYSTEMS_DEFAULTS_H

#include "unified-config-manager.h"

// Diagnostic System Defaults
#define DIAGNOSTIC_ENABLED_DEFAULT 1
#define DIAGNOSTIC_LOG_LEVEL_DEFAULT 2
#define DIAGNOSTIC_SAMPLING_RATE_DEFAULT 100
#define DIAGNOSTIC_TIMEOUT_MS_DEFAULT 5000
#define DIAGNOSTIC_MAX_REPORTS_DEFAULT 100

// Monitoring System Defaults
#define MONITORING_ENABLED_DEFAULT 1
#define MONITORING_UPDATE_INTERVAL_MS_DEFAULT 1000
#define MONITORING_RETENTION_HOURS_DEFAULT 24
#define MONITORING_ALERT_THRESHOLD_DEFAULT 80
#define MONITORING_MAX_METRICS_DEFAULT 50

// Debugging Framework Defaults
#define DEBUGGING_ENABLED_DEFAULT 1
#define DEBUGGING_LOG_LEVEL_DEFAULT 1
#define DEBUGGING_MAX_TRACES_DEFAULT 1000
#define DEBUGGING_BREAKPOINT_LIMIT_DEFAULT 50
#define DEBUGGING_VARIABLE_WATCH_LIMIT_DEFAULT 25

// Optimization System Defaults
#define OPTIMIZATION_ENABLED_DEFAULT 1
#define OPTIMIZATION_LEVEL_DEFAULT 2
#define OPTIMIZATION_SAMPLING_INTERVAL_MS_DEFAULT 500
#define OPTIMIZATION_RESOURCE_THRESHOLD_DEFAULT 85
#define OPTIMIZATION_AUTOTUNE_ENABLED_DEFAULT 1

// Health Monitor Defaults
#define HEALTH_MONITOR_ENABLED_DEFAULT 1
#define HEALTH_MONITOR_INTERVAL_MS_DEFAULT 1000
#define HEALTH_CRITICAL_THRESHOLD_DEFAULT 30
#define HEALTH_WARNING_THRESHOLD_DEFAULT 60
#define HEALTH_RETENTION_MINUTES_DEFAULT 1440  // 24 hours

// Resource Manager Defaults
#define RESOURCE_MANAGER_ENABLED_DEFAULT 1
#define RESOURCE_SAMPLING_INTERVAL_MS_DEFAULT 100
#define RESOURCE_OPTIMIZATION_THRESHOLD_DEFAULT 85
#define RESOURCE_MAX_ALLOCATED_DEFAULT 80

// Function to initialize default configuration values
int init_advanced_systems_defaults(unified_config_manager_t* cfg_mgr);

#endif // ADVANCED_SYSTEMS_DEFAULTS_H